"""Pick the fixed few-shot demonstrations for the LLM baseline (D-020) and save their ids.

Usage:
    python scripts/select_few_shot.py [--config configs/llm.yaml]

Only ids are written (configs/few_shot_ids.yaml): tweet text is never committed (D-004). The chosen
examples are printed so a human can review them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from hinglish_sentiment.baselines.tfidf import out_of_fold_gold_probability  # noqa: E402
from hinglish_sentiment.config import load_config, resolve  # noqa: E402
from hinglish_sentiment.llm.prompts import select_few_shot  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/llm.yaml")
    cfg = load_config(parser.parse_args().config)
    fs = cfg["few_shot"]

    train = pd.read_parquet(resolve(cfg["paths"]["processed_dir"]) / "train.parquet").reset_index(drop=True)
    print("Out-of-fold label confidence on train (5-fold TF-IDF) ...")
    train["gold_p"] = out_of_fold_gold_probability(train.text, train.label_id, seed=cfg["seed"], **fs["tfidf_params"])
    pool = train[train.gold_p >= fs["min_gold_probability"]]
    print(f"{len(pool):,}/{len(train):,} train tweets pass gold-probability >= {fs['min_gold_probability']}: "
          f"{pool.label.value_counts().to_dict()}")
    examples = select_few_shot(pool, fs["per_class"], fs["seed"])

    with open(resolve(fs["ids_path"]), "w", encoding="utf-8") as fh:
        fh.write("# Generated by scripts/select_few_shot.py -- the few-shot demonstrations (train ids, in prompt order).\n")
        yaml.safe_dump({"ids": examples.id.tolist(), "min_gold_probability": fs["min_gold_probability"],
                        "seed": fs["seed"]}, fh, sort_keys=False)
    for ex in examples.itertuples():
        print(f"\n[{ex.label} · p={ex.gold_p:.2f} · {ex.id}]\n{ex.text}")
    print(f"\nSaved {len(examples)} ids -> {fs['ids_path']}")


if __name__ == "__main__":
    main()
